services:
  backend:
    build:
      context: ./backend  # Katalog backendu
    image: strapi-backend  # Nazwa obrazu dla backendu
    env_file:
      - /backend/.env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: fbe-solutions_db  # Zmieniamy na fbe-solutions_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
    depends_on:
      - db  # Umożliwia uruchomienie backendu po uruchomieniu bazy danych
    ports:
      - "1337:1337"  # Eksport portu 1337 na hosta
    networks:
      - fbe-solutions  # Przypisanie do sieci

  frontend:
    build:
      context: ./frontend  # Katalog frontendu
    image: angular-frontend  # Nazwa obrazu dla frontendu
    ports:
      - "4200:80"  # Eksport portu 4200 na hosta
    networks:
      - fbe-solutions  # Przypisanie do sieci

  db:
    image: postgres:13  # Użycie obrazu PostgreSQL
    environment:
      POSTGRES_USER: strapi_user  # Użytkownik bazy danych
      POSTGRES_PASSWORD: strapi_password  # Hasło bazy danych
      POSTGRES_DB: fbe-solutions_db  # Zmieniamy na fbe-solutions_db
    volumes:
      - db_data:/var/lib/postgresql/data  # Trwały wolumen na dane bazy
    networks:
      - fbe-solutions  # Przypisanie do sieci

networks:
  fbe-solutions:  # Deklaracja sieci

volumes:
  db_data: