version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - frontend

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend