services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Eksport portu 80 na hoście
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fbe-solutions

  backend:
    build:
      context: ./backend
    image: strapi-backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: fbe-solutions_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
    depends_on:
      - db
    networks:
      - fbe-solutions

  frontend:
    build:
      context: ./frontend
    image: angular-frontend
    ports:
      - "4000:4000"
    networks:
      - fbe-solutions
    depends_on:
      - backend
    command: ["node", "dist/fbe-solutions/server/main.js"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: fbe-solutions_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fbe-solutions

networks:
  fbe-solutions:
    driver: bridge

volumes:
  db_data:
