name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and Deploy
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  remote: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  privateKey: ${{ secrets.VPS_PRIVATE_KEY }}
                  script: |
                      cd /path/to/your/project  
                      docker-compose down
                      docker-compose up -d --build
