name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2  # Krok 1: Klonowanie repozytorium

            - name: Copy files to VPS
              uses: garygrossgarten/github-action-scp@release  # Użycie akcji do kopiowania plików
              with:
                  remote: ${{ secrets.VPS_IP }}  # IP twojego VPS
                  username: ${{ secrets.VPS_USER }}  # Użytkownik VPS
                  privateKey: ${{ secrets.VPS_PRIVATE_KEY }}  # Klucz prywatny
                  source: '.'  # Katalog źródłowy do skopiowania
                  target: '/fbe-solutions'  # Docelowy katalog na VPS

            - name: SSH and Deploy
              uses: webfactory/ssh-agent@v0.5.3  # Użycie akcji SSH
              with:
                  ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}
              run: |  # Użycie 'run' do wykonania skryptu
                  cd /fbe-solutions  # Zmiana katalogu na serwerze do skopiowanego folderu
                  docker-compose down  # Zatrzymanie kontenerów
                  docker-compose up -d --build  # Uruchomienie kontenerów w tle